### PR TITLE
Update to 3.9.x with OnLogout

### PR DESCRIPTION
**Pull request by Solethia**
- Updated to spt 3.9.X
- Added OnLogout to save backup on logout 
- Updated readme

### CODE REVIEW

**Comment by Solethia** [comment]
Backup test
image
image
image
image
image

**Comment by Solethia** [comment]
Restore test
image
image

**Comment by Solethia** [comment]
Seems to be an issue when disabled.
The postdbload would not load path variables when disabled, but the routes would still be registered and fire events where when trying to create backup based on event it would fail because the path variables would be undefined.

**Comment by Solethia** [comment]
Test disabled
image

**Review by dvize — APPROVED** [review]
Thanks for the updates for 3.9

**Pull request merged**
